//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMgt.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStudent
    {
        public int Id { get; set; }
        public int RegId { get; set; }
        public int CourseId { get; set; }
        public int SId { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual Student Student { get; set; }
    }
}
